# Narrow, hash-pinned modifications; replay from pristine copies on configure.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../native/gme-taps/patches.json" patches)
string(JSON file_count LENGTH "${patches}")
math(EXPR last "${file_count} - 1")
foreach(index RANGE 0 ${last})
  string(JSON name GET "${patches}" ${index} file)
  string(JSON expected GET "${patches}" ${index} sha256)
  set(source "${gme_SOURCE_DIR}/gme/${name}")
  set(pristine "${source}.bitmusic-original")
  if(NOT EXISTS "${pristine}")
    configure_file("${source}" "${pristine}" COPYONLY)
  endif()
  file(SHA256 "${pristine}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Unexpected libgme source for ${name}; review taps patch against upstream")
  endif()
  file(READ "${pristine}" content)
  string(JSON edit_count LENGTH "${patches}" ${index} edits)
  math(EXPR edit_last "${edit_count} - 1")
  foreach(edit RANGE 0 ${edit_last})
    string(JSON before GET "${patches}" ${index} edits ${edit} 0)
    string(JSON after GET "${patches}" ${index} edits ${edit} 1)
    string(FIND "${content}" "${before}" found)
    if(found LESS 0)
      message(FATAL_ERROR "libgme patch anchor missing: ${name}/${edit}")
    endif()
    string(REPLACE "${before}" "${after}" content "${content}")
  endforeach()
  file(WRITE "${source}.bitmusic-new" "${content}")
  configure_file("${source}.bitmusic-new" "${source}" COPYONLY)
endforeach()
# Upstream's ELF/macOS export lists otherwise hide the optional C tap API.
set(tap_exports bm_taps_create bm_taps_delete bm_taps_enter bm_taps_reset bm_taps_read bm_notes_create bm_notes_delete bm_notes_enter bm_notes_reset bm_notes_read)
if(APPLE OR UNIX)
  set(symbols "${gme_BINARY_DIR}/gme/gme.sym")
  file(READ "${symbols}" exports)
  if(APPLE)
    foreach(symbol IN LISTS tap_exports)
      string(APPEND exports "_${symbol}\n")
    endforeach()
  else()
    string(REPLACE "  local: *;" "    bm_taps_create; bm_taps_delete; bm_taps_enter; bm_taps_reset; bm_taps_read; bm_notes_create; bm_notes_delete; bm_notes_enter; bm_notes_reset; bm_notes_read;\n  local: *;" exports "${exports}")
  endif()
  file(WRITE "${symbols}" "${exports}")
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/../native/gme-taps/Ym2413_Emu.cpp" "${gme_SOURCE_DIR}/gme/Ym2413_Emu.cpp" COPYONLY)
foreach(target gme_static gme_shared)
  if(TARGET ${target})
    target_sources(${target} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../native/gme-taps/taps.cpp" "${CMAKE_CURRENT_LIST_DIR}/../native/gme-taps/notes.cpp")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../native/gme-taps" "${gme_SOURCE_DIR}/gme")
    target_compile_features(${target} PRIVATE cxx_std_17)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(${target} PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:-fexceptions>")
    endif()
  endif()
endforeach()
